name: On push branch - develop or develop-*
on:
  push:
    branches: [develop, develop-*]
  
jobs:
  hello-word:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2         

        - run: echo "HOLA MUNDO"
        
        - name: Branch name
          run: echo running on branch ${GITHUB_REF##*/}
