name: On push branch - echo name
on:
  push
  
jobs:
  hello-word:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2         
        
        - name: Branch name ${GITHUB_REF##*/}
          run: echo running on branch ${GITHUB_REF##*/}
          
        - name: Branch name  ${github.head_ref}
          run: echo running on branch ${{github.head_ref}}
