name: On create branch - Rename version pom.xml

on:
  create:
    branches:
      - main
jobs:
  extract-suffix-name-branch:
      runs-on: ubuntu-latest
      outputs:
        suffix_name: ${{ steps.get-id.outputs.id }}
      steps:
        - uses: actions/checkout@v2         
          
        - name: Get branch name
          id: branch-name
          uses: tj-actions/branch-names@v5.1

        - id: get-id
          run: |
            id=$(echo ${{ steps.branch-name.outputs.current_branch }} | cut -d/ -f2 | cut -d- -f1-2)
            echo "::set-output name=id::$id"
        
  extract-preffix-name-pom-version:
      runs-on: ubuntu-latest
      outputs:
        preffix_name: ${{ steps.get-id.outputs.id }}
      steps:
        - uses: actions/checkout@v2        
                
        - name: Extract Maven project version
          working-directory: ./example3-gitactions
          run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
          id: project_version
        - run: echo "Maven project version is ${{ steps.project_version.outputs.version }}"

        - id: get-id
          run: |
            id=$(echo ${{ steps.project_version.outputs.version }} | cut -d- -f1)
            echo "::set-output name=id::$id"       
        
  rename-pom-version-and-commit:
      needs: [extract-preffix-name-pom-version, extract-suffix-name-branch]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2          
        
        - name: Set up JDK 1.11
          uses: actions/setup-java@v1
          with:
            java-version: 1.11             
              
        - name: set version pom
          working-directory: ./example3-gitactions
          run: mvn -B versions:set -DnewVersion=${{ needs.extract-preffix-name-pom-version.outputs.preffix_name }}-${{ needs.extract-suffix-name-branch.outputs.suffix_name }}-SNAPSHOT -DgenerateBackupPoms=false
         
        - name: Commit new version pom.xml - branch
          run: |
            git config --global user.name 'Roberto'
            git config --global user.email 'roberto-pf@github.com'
            git add .
            git commit -am "Automated report"
            git push
            
        - name: mvn package
          run: mvn -B package --file example3-gitactions/pom.xml
